version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: webuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: webdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://webuser:1234@db:5432/webdb
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: next_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: